## UniFlex Agent config file

config:
  name: 'RadioSlicer'
  info: 'local controller program running on WiFi AP performing radio slicing (based on hMAC)'
  iface: 'lo'
  sub: "tcp://127.0.0.1:8995"
  pub: "tcp://127.0.0.1:8985"

#remove broker if already started
broker:
  xpub: "tcp://127.0.0.1:8995"
  xsub: "tcp://127.0.0.1:8985"

control_applications:
  myController:
      file : local_radio_slicer.py
      class_name : LocalRadioSlicer
      kwargs : {}

modules:
  wifiath:
      module : uniflex_module_wifi_ath
      class_name : Ath9kModule
      devices : ['phy0']
